[package]
name = "topology_proximity_comm"
version = "0.1.0"
edition = "2021"
default-run = "main_sub"

[[bin]]
name = "main_sub"
path = "src/bin/main_sub.rs"

[[bin]]
name = "main_pub"
path = "src/bin/main_pub.rs"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "time"] }
zenoh = { version = "1.9", features = ["unstable"] }
